### PR TITLE
Update apply_incr_noahmp_snow.f90

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
Change from `landinc` to `snowinc`

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
@ClaraDraper-NOAA are you the owner here? I don't have the ability to request anyone to review.

**Comment by ClaraDraper-NOAA** [comment]
> @ClaraDraper-NOAA are you the owner here? I don't have the ability to request anyone to review.

I am, and will add reviewers (once I sort out an access issue).

**Comment by CoryMartin-NOAA** [comment]
Thanks!

**Comment by ClaraDraper-NOAA** [comment]
> Thanks!

Looks like I have to re-add people before they can review (and they need to accept, I think). Is it urgent?

**Comment by CoryMartin-NOAA** [comment]
it can wait until next week, it is 4:20 on a Friday here :-)

**Comment by ClaraDraper-NOAA** [comment]
Making this change here will also require the same change in at least one other repo to keep the offline workflow working. I don't mind doing that, since I need to update the JEDI version anyway. Jiarui has also still not tested his checksum change in the full workflow, so I suppose I can do that too.

**Comment by CoryMartin-NOAA** [comment]
I did this as a one-liner, I would've preferred to make the prefix a namelist option, but I wasn't sure that was worth the effort.

**Comment by ClaraDraper-NOAA** [comment]
> I did this as a one-liner, I would've preferred to make the prefix a namelist option, but I wasn't sure that was worth the effort.

I might try to match it to what we do in UFS_UTILS, which is a mess of namelist input and hardcoded file names. I asked Yuan to make it more consistent, so maybe I'll copy her solution here. Either way, I'll take care of it (early next week).

**Comment by CoryMartin-NOAA** [comment]
Perfect, thanks!

**Comment by ClaraDraper-NOAA** [comment]
Merged so as not to hold-up GDAS development. This change will require some updates in the offline land workflow before the hash can be updated.

**Pull request merged**
